name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-item:
        description: "The artifact downloading files"
        required: false
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-item }}
      - name: Output information
        run: echo "Deploying successfully"