name : Reusable deploy
on: 
  workflow_call:
    inputs: 
      artifact-item:
      description: "the artifact downloading files"
      required: false
      default: dist
      type: string
jobs:
      Deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/download-artifact@v4
          with: 
            name: ${{ inputs.artifact-item }} 
        - name: Output information
          run: echo "Deploying successfully"